name: Lint

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install --yes luarocks
          luarocks install --local luacheck
          echo "$HOME/.luarocks/bin" >> "$GITHUB_PATH"
      - name: Lint
        run: make lint

  stylua:
    name: stylua
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ github.token }}
          version: latest
          args: --color always --check lua/
